/* Autogenerated file. Do not edit manually. */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from './common';

export interface PLUMEGatewayInterface extends utils.Interface {
  functions: {
    'depositPLUME(address)': FunctionFragment;
    'redeemPLUME(uint256,address)': FunctionFragment;
    'requestRedeemPLUME(uint256,address,uint256)': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'depositPLUME'
      | 'redeemPLUME'
      | 'requestRedeemPLUME',
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: 'depositPLUME',
    values: [string],
  ): string;
  encodeFunctionData(
    functionFragment: 'redeemPLUME',
    values: [BigNumberish, string],
  ): string;
  encodeFunctionData(
    functionFragment: 'requestRedeemPLUME',
    values: [BigNumberish, string, BigNumberish],
  ): string;

  decodeFunctionResult(
    functionFragment: 'depositPLUME',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'redeemPLUME',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'requestRedeemPLUME',
    data: BytesLike,
  ): Result;

  events: {};
}

export interface PLUMEGateway extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PLUMEGatewayInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    depositPLUME(
      onBehalfOf: string,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<ContractTransaction>;

    redeemPLUME(
      requestIndex: BigNumberish,
      onBehalfOf: string,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    requestRedeemPLUME(
      shares: BigNumberish,
      onBehalfOf: string,
      minAssets: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;
  };

  depositPLUME(
    onBehalfOf: string,
    overrides?: PayableOverrides & { from?: string },
  ): Promise<ContractTransaction>;

  redeemPLUME(
    requestIndex: BigNumberish,
    onBehalfOf: string,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  requestRedeemPLUME(
    shares: BigNumberish,
    onBehalfOf: string,
    minAssets: BigNumberish,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  callStatic: {
    depositPLUME(
      onBehalfOf: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    redeemPLUME(
      requestIndex: BigNumberish,
      onBehalfOf: string,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    requestRedeemPLUME(
      shares: BigNumberish,
      onBehalfOf: string,
      minAssets: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    depositPLUME(
      onBehalfOf: string,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<BigNumber>;

    redeemPLUME(
      requestIndex: BigNumberish,
      onBehalfOf: string,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    requestRedeemPLUME(
      shares: BigNumberish,
      onBehalfOf: string,
      minAssets: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    depositPLUME(
      onBehalfOf: string,
      overrides?: PayableOverrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    redeemPLUME(
      requestIndex: BigNumberish,
      onBehalfOf: string,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    requestRedeemPLUME(
      shares: BigNumberish,
      onBehalfOf: string,
      minAssets: BigNumberish,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;
  };
}
