/* Autogenerated file. Do not edit manually. */
/* eslint-disable */
export type { WrappedTokenGatewayV3 } from './WrappedTokenGatewayV3';
export * as factories from './factories';
export { WrappedTokenGatewayV3__factory } from './factories/WrappedTokenGatewayV3__factory';
