/* Autogenerated file. Do not edit manually. */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers';
import type { FunctionFragment, Result } from '@ethersproject/abi';
import type { Listener, Provider } from '@ethersproject/providers';
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from './common';

export declare namespace Looping {
  export type LoopParamsStruct = {
    initialAmount: BigNumberish;
    targetHealthFactor: BigNumberish;
    numLoops: BigNumberish;
  };

  export type LoopParamsStructOutput = [BigNumber, number, number] & {
    initialAmount: BigNumber;
    targetHealthFactor: number;
    numLoops: number;
  };
}

export interface LoopingInterface extends utils.Interface {
  functions: {
    'aavePool()': FunctionFragment;
    'calculateBorrowAmount(uint256,address,address,uint256,uint256)': FunctionFragment;
    'calculateBorrowAmountSingleAsset(uint256,address,uint256,uint256)': FunctionFragment;
    'leveragePositionMultiSwap(address,address,bytes,(uint256,uint16,uint16))': FunctionFragment;
    'leveragePositionSingleAsset(address,(uint256,uint16,uint16))': FunctionFragment;
    'leveragePositionSingleSwap(address,address,address,bool,(uint256,uint16,uint16))': FunctionFragment;
    'oracleDecimals()': FunctionFragment;
    'priceOracle()': FunctionFragment;
    'swapRouter()': FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | 'aavePool'
      | 'calculateBorrowAmount'
      | 'calculateBorrowAmountSingleAsset'
      | 'leveragePositionMultiSwap'
      | 'leveragePositionSingleAsset'
      | 'leveragePositionSingleSwap'
      | 'oracleDecimals'
      | 'priceOracle'
      | 'swapRouter',
  ): FunctionFragment;

  encodeFunctionData(functionFragment: 'aavePool', values?: undefined): string;
  encodeFunctionData(
    functionFragment: 'calculateBorrowAmount',
    values: [BigNumberish, string, string, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'calculateBorrowAmountSingleAsset',
    values: [BigNumberish, string, BigNumberish, BigNumberish],
  ): string;
  encodeFunctionData(
    functionFragment: 'leveragePositionMultiSwap',
    values: [string, string, BytesLike, Looping.LoopParamsStruct],
  ): string;
  encodeFunctionData(
    functionFragment: 'leveragePositionSingleAsset',
    values: [string, Looping.LoopParamsStruct],
  ): string;
  encodeFunctionData(
    functionFragment: 'leveragePositionSingleSwap',
    values: [string, string, string, boolean, Looping.LoopParamsStruct],
  ): string;
  encodeFunctionData(
    functionFragment: 'oracleDecimals',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'priceOracle',
    values?: undefined,
  ): string;
  encodeFunctionData(
    functionFragment: 'swapRouter',
    values?: undefined,
  ): string;

  decodeFunctionResult(functionFragment: 'aavePool', data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: 'calculateBorrowAmount',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'calculateBorrowAmountSingleAsset',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'leveragePositionMultiSwap',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'leveragePositionSingleAsset',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'leveragePositionSingleSwap',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'oracleDecimals',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(
    functionFragment: 'priceOracle',
    data: BytesLike,
  ): Result;
  decodeFunctionResult(functionFragment: 'swapRouter', data: BytesLike): Result;

  events: {};
}

export interface Looping extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: LoopingInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>,
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>,
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    aavePool(overrides?: CallOverrides): Promise<[string]>;

    calculateBorrowAmount(
      supplyAmount: BigNumberish,
      supplyToken: string,
      borrowToken: string,
      ltv: BigNumberish,
      targetHealthFactor: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    calculateBorrowAmountSingleAsset(
      amount: BigNumberish,
      token: string,
      ltv: BigNumberish,
      targetHealthFactor: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<[BigNumber]>;

    leveragePositionMultiSwap(
      supplyToken: string,
      borrowToken: string,
      path: BytesLike,
      params: Looping.LoopParamsStruct,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    leveragePositionSingleAsset(
      token: string,
      params: Looping.LoopParamsStruct,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    leveragePositionSingleSwap(
      supplyToken: string,
      borrowToken: string,
      maverickPool: string,
      isSupplyTokenA: boolean,
      params: Looping.LoopParamsStruct,
      overrides?: Overrides & { from?: string },
    ): Promise<ContractTransaction>;

    oracleDecimals(overrides?: CallOverrides): Promise<[BigNumber]>;

    priceOracle(overrides?: CallOverrides): Promise<[string]>;

    swapRouter(overrides?: CallOverrides): Promise<[string]>;
  };

  aavePool(overrides?: CallOverrides): Promise<string>;

  calculateBorrowAmount(
    supplyAmount: BigNumberish,
    supplyToken: string,
    borrowToken: string,
    ltv: BigNumberish,
    targetHealthFactor: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  calculateBorrowAmountSingleAsset(
    amount: BigNumberish,
    token: string,
    ltv: BigNumberish,
    targetHealthFactor: BigNumberish,
    overrides?: CallOverrides,
  ): Promise<BigNumber>;

  leveragePositionMultiSwap(
    supplyToken: string,
    borrowToken: string,
    path: BytesLike,
    params: Looping.LoopParamsStruct,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  leveragePositionSingleAsset(
    token: string,
    params: Looping.LoopParamsStruct,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  leveragePositionSingleSwap(
    supplyToken: string,
    borrowToken: string,
    maverickPool: string,
    isSupplyTokenA: boolean,
    params: Looping.LoopParamsStruct,
    overrides?: Overrides & { from?: string },
  ): Promise<ContractTransaction>;

  oracleDecimals(overrides?: CallOverrides): Promise<BigNumber>;

  priceOracle(overrides?: CallOverrides): Promise<string>;

  swapRouter(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    aavePool(overrides?: CallOverrides): Promise<string>;

    calculateBorrowAmount(
      supplyAmount: BigNumberish,
      supplyToken: string,
      borrowToken: string,
      ltv: BigNumberish,
      targetHealthFactor: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    calculateBorrowAmountSingleAsset(
      amount: BigNumberish,
      token: string,
      ltv: BigNumberish,
      targetHealthFactor: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    leveragePositionMultiSwap(
      supplyToken: string,
      borrowToken: string,
      path: BytesLike,
      params: Looping.LoopParamsStruct,
      overrides?: CallOverrides,
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    leveragePositionSingleAsset(
      token: string,
      params: Looping.LoopParamsStruct,
      overrides?: CallOverrides,
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    leveragePositionSingleSwap(
      supplyToken: string,
      borrowToken: string,
      maverickPool: string,
      isSupplyTokenA: boolean,
      params: Looping.LoopParamsStruct,
      overrides?: CallOverrides,
    ): Promise<[BigNumber, BigNumber, BigNumber]>;

    oracleDecimals(overrides?: CallOverrides): Promise<BigNumber>;

    priceOracle(overrides?: CallOverrides): Promise<string>;

    swapRouter(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    aavePool(overrides?: CallOverrides): Promise<BigNumber>;

    calculateBorrowAmount(
      supplyAmount: BigNumberish,
      supplyToken: string,
      borrowToken: string,
      ltv: BigNumberish,
      targetHealthFactor: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    calculateBorrowAmountSingleAsset(
      amount: BigNumberish,
      token: string,
      ltv: BigNumberish,
      targetHealthFactor: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<BigNumber>;

    leveragePositionMultiSwap(
      supplyToken: string,
      borrowToken: string,
      path: BytesLike,
      params: Looping.LoopParamsStruct,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    leveragePositionSingleAsset(
      token: string,
      params: Looping.LoopParamsStruct,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    leveragePositionSingleSwap(
      supplyToken: string,
      borrowToken: string,
      maverickPool: string,
      isSupplyTokenA: boolean,
      params: Looping.LoopParamsStruct,
      overrides?: Overrides & { from?: string },
    ): Promise<BigNumber>;

    oracleDecimals(overrides?: CallOverrides): Promise<BigNumber>;

    priceOracle(overrides?: CallOverrides): Promise<BigNumber>;

    swapRouter(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    aavePool(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    calculateBorrowAmount(
      supplyAmount: BigNumberish,
      supplyToken: string,
      borrowToken: string,
      ltv: BigNumberish,
      targetHealthFactor: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    calculateBorrowAmountSingleAsset(
      amount: BigNumberish,
      token: string,
      ltv: BigNumberish,
      targetHealthFactor: BigNumberish,
      overrides?: CallOverrides,
    ): Promise<PopulatedTransaction>;

    leveragePositionMultiSwap(
      supplyToken: string,
      borrowToken: string,
      path: BytesLike,
      params: Looping.LoopParamsStruct,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    leveragePositionSingleAsset(
      token: string,
      params: Looping.LoopParamsStruct,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    leveragePositionSingleSwap(
      supplyToken: string,
      borrowToken: string,
      maverickPool: string,
      isSupplyTokenA: boolean,
      params: Looping.LoopParamsStruct,
      overrides?: Overrides & { from?: string },
    ): Promise<PopulatedTransaction>;

    oracleDecimals(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    priceOracle(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapRouter(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
